import * as React from "react";
function cx(...parts: Array<string | false | null | undefined>) { return parts.filter(Boolean).join(" "); }

type Ctx = { value?: string; onValueChange?: (v:string)=>void; open:boolean; setOpen:(v:boolean)=>void };
const SelectContext = React.createContext<Ctx | null>(null);
export function Select({ value, onValueChange, children }: { value?: string; onValueChange?: (value:string)=>void; children: React.ReactNode; }) { const [open, setOpen] = React.useState(false); return <SelectContext.Provider value={{ value, onValueChange, open, setOpen }}>{children}</SelectContext.Provider>; }
export const SelectTrigger = React.forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement>>(function SelectTrigger({ className, children, ...props }, ref){ const ctx=React.useContext(SelectContext)!; return <button ref={ref} type="button" onClick={()=>ctx.setOpen(!ctx.open)} className={cx('flex h-10 w-full items-center justify-between rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-100', className)} {...props}>{children}<span className="ml-2 text-slate-400">▾</span></button>; });
export function SelectValue({ placeholder }: { placeholder?: string }) { const ctx=React.useContext(SelectContext)!; return <span>{ctx.value || placeholder || 'Select'}</span>; }
export function SelectContent({ className, children }: { className?: string; children: React.ReactNode }) { const ctx=React.useContext(SelectContext)!; if(!ctx.open) return null; return <div className={cx('relative z-50 mt-1 rounded-lg border border-slate-700 bg-slate-900 p-1 shadow-xl', className)}>{children}</div>; }
export function SelectItem({ value, className, children }: { value: string; className?: string; children: React.ReactNode }) { const ctx=React.useContext(SelectContext)!; const active = ctx.value===value; return <button type="button" className={cx('flex w-full items-center rounded-md px-3 py-2 text-sm text-left text-slate-200 hover:bg-slate-800', active&&'bg-slate-800', className)} onClick={()=>{ctx.onValueChange?.(value); ctx.setOpen(false);}}>{children}</button>; }
export function SelectGroup({children}:{children:React.ReactNode}){ return <div>{children}</div>; }
